### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by ljhpmos** [stmilab/ArterialNet#1]
hi, I am interested in your work,can you tell me which part data you use for the ABP waveforms reconstitution? Thank you for your help

**Comment by Innoversa** [comment]
Hi, thank you so much for your interest! In utils/mimic_file_list.txt you will find the list of patient visits from the public MIMIC III dataset. You can request access to the MIMIC III dataset via https://physionet.org/content/mimiciii/1.4/.
