### ISSUE TITLE
sicong_utilm module

### ISSUE THREAD

**Issue by ascas666** [stmilab/ArterialNet#3]
it seems that there is no sicong_utilm module in the code

**Comment by Innoversa** [comment]
Hi, 
Thanks for catching that! 
The `sicong_util.py` is a helper script containing a few miscellaneous utilities. I only use it to report progress and exceptions by generating emails. I've added it to the repository, and you can find it [here](https://github.com/stmilab/ArterialNet/blob/main/utils/sicong_util.py). 
Best,
Sicong
